server:
  port: 9090
#my:
#  key: 10
#  key2: 20
#  spring.application.name=spring-book-demo
#  server.port=9090
#  spring.datasource.url=jdbc:mysql://127.0.0.1:3306/testdb?characterEncoding=utf8&useSSL=false
#  spring.datasource.username=root
#  spring.datasource.password=fA810233
#  my.key=1
#  my.key2=true
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/book_test?characterEncoding=utf8&useSSL=false
    username: root
    password: fA810233
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: spring-book-demo

mybatis:
  configuration: # 配置打印 MyBatis⽇志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #自动转驼峰
  mapper-locations: classpath:mapper/**.xml
